<a href="https://colab.research.google.com/github/manavbahuguna/manavbahuguna/blob/main/OneHotEncoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/archive (1).zip')

In [ ]:
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
df.iloc[2,:]

User ID            15668575
Gender               Female
Age                      26
EstimatedSalary       43000
Purchased                 0
Name: 2, dtype: object

In [ ]:
df['Purchased'].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

OHE using pandas (Not Recommended)

In [ ]:
pd.get_dummies(df,columns=['Purchased','Gender'],drop_first = True)

      User ID  Age  EstimatedSalary  Purchased_1  Gender_Male
0    15624510   19            19000        False         True
1    15810944   35            20000        False         True
2    15668575   26            43000        False        False
3    15603246   27            57000        False        False
4    15804002   19            76000        False         True
..        ...  ...              ...          ...          ...
395  15691863   46            41000         True        False
396  15706071   51            23000         True         True
397  15654296   50            20000         True        False
398  15755018   36            33000        False         True
399  15594041   49            36000         True        False

[400 rows x 5 columns]

OHE Using sklean